apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>K8S HW5</title>
    </head>
    <body>
      <h1>Kubernetes!</h1>
      <p>Страница загружена из ConfigMap.</p>
    </body>
    </html>
