apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-app-tls
spec:
  ingressClassName: public
  tls:
  - secretName: tls-secret

  rules:
  - host: andrey.netology.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-app-service
            port:
              number: 80
